// <auto-generated />
using System;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Laptops",
                            CreatedAt = new DateTime(2025, 9, 16, 22, 55, 34, 882, DateTimeKind.Utc).AddTicks(1850),
                            Description = "Ultrabook premium con pantalla InfinityEdge",
                            IsActive = true,
                            Name = "Laptop Dell XPS 13",
                            Price = 1299.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accesorios",
                            CreatedAt = new DateTime(2025, 9, 16, 22, 55, 34, 882, DateTimeKind.Utc).AddTicks(1853),
                            Description = "Mouse ergonómico inalámbrico profesional",
                            IsActive = true,
                            Name = "Mouse Logitech MX Master 3",
                            Price = 99.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Accesorios",
                            CreatedAt = new DateTime(2025, 9, 16, 22, 55, 34, 882, DateTimeKind.Utc).AddTicks(1855),
                            Description = "Teclado mecánico inalámbrico 75%",
                            IsActive = true,
                            Name = "Teclado Mecánico Keychron K2",
                            Price = 79.99m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
